# arch-nspawn
# Autogenerated from man page /usr/share/man/man1/arch-nspawn.1.gz
complete -c arch-nspawn -s C
complete -c arch-nspawn -s M
complete -c arch-nspawn -s c
complete -c arch-nspawn -s f
complete -c arch-nspawn -s s
complete -c arch-nspawn -s h

