# arch-rebuild-order
# Autogenerated from man page /usr/share/man/man1/arch-rebuild-order.1.gz
complete -c arch-rebuild-order -l d -l dotfile
complete -c arch-rebuild-order -l dbpath
complete -c arch-rebuild-order -l repos
complete -c arch-rebuild-order -l no-reverse-depends
complete -c arch-rebuild-order -l with-check-depends
complete -c arch-rebuild-order -s V -l version
complete -c arch-rebuild-order -s h -l help

