# arch-repro-status
# Autogenerated from man page /usr/share/man/man1/arch-repro-status.1.gz
complete -c arch-repro-status -s q -l quiet -d 'Disables logging'
complete -c arch-repro-status -s v -l verbose -d 'Increases the logging verbosity'
complete -c arch-repro-status -s a -l all -d 'Checks all of the packages on the system'
complete -c arch-repro-status -s m -l maintainer -d 'Sets the username of the maintainer [env: MAINTAINER=]'
complete -c arch-repro-status -s r -l rebuilderd -d 'Sets the address of the rebuilderd instance [env: REBUILDERD=] [default: http…'
complete -c arch-repro-status -s b -l dbpath -d 'Sets the path to the pacman database [env: DBPATH=] [default: /var/lib/pacman]'
complete -c arch-repro-status -l repos -d 'Sets the repositories to query [default: core,extra,multilib]'
complete -c arch-repro-status -s n -l pkgnames -d 'Sets the comma-delimited list of packages to query for [env: PKGNAME=]'
complete -c arch-repro-status -s f -l filter -d 'Sets the filter for package status [env: FILTER=] [possible values: GOOD, BAD…'
complete -c arch-repro-status -s i -l inspect -d 'Views the build log or diffoscope of the interactively selected package'
complete -c arch-repro-status -s p -l pager -d 'Sets the pager for viewing files [env: PAGER=] [default: less]'
complete -c arch-repro-status -s c -l cache-dir -d 'Sets the cache directory for log files [env: CACHE_DIR=]'
complete -c arch-repro-status -s h -l help -d 'Print help information'
complete -c arch-repro-status -s V -l version -d 'Print version information'

