# checkpkg
# Autogenerated from man page /usr/share/man/man1/checkpkg.1.gz
complete -c checkpkg -s r -l rmdir
complete -c checkpkg -s w -l warn
complete -c checkpkg -s M -l makepkg-config
complete -c checkpkg -s h -l help

