# diffpkg
# Autogenerated from man page /usr/share/man/man1/diffpkg.1.gz
complete -c diffpkg -s M -l makepkg-config
complete -c diffpkg -s P -l pool
complete -c diffpkg -s v -l verbose
complete -c diffpkg -s h -l help
complete -c diffpkg -l color
complete -c diffpkg -s u -s U -l unified
complete -c diffpkg -s y -l side-by-side
complete -c diffpkg -s W -l width
complete -c diffpkg -s l -l list
complete -c diffpkg -s d -l diffoscope
complete -c diffpkg -s p -l pkginfo
complete -c diffpkg -s b -l buildinfo

