# hardinfo2
# Autogenerated from man page /usr/share/man/man1/hardinfo2.1.gz
complete -c hardinfo2 -s h -l help -d 'Show help options'
complete -c hardinfo2 -s q -l quiet -d 'do not print status messages to standard output'
complete -c hardinfo2 -s r -l generate-report -d 'creates a report and prints to standard output'
complete -c hardinfo2 -s f -l report-format -d 'chooses a report format (text, html)'
complete -c hardinfo2 -s t -l topic -d 'search for a topic in CLI report (-t getlist shows available)'
complete -c hardinfo2 -s c -l topic-cache -d 'search for a topic in Cached CLI report (-t getlist shows available)'
complete -c hardinfo2 -s b -l run-benchmark -d 'run a specific benchmark eg'
complete -c hardinfo2 -s u -l user-note -d 'adds a user note to data send to server.  When added eg'
complete -c hardinfo2 -s g -l result-format -d 'chooses a result format (short, conf, shell)'
complete -c hardinfo2 -s n -l max-results -d 'maximum number of benchmark results to include (-1 for no limit, default is 5…'
complete -c hardinfo2 -s v -l version -d 'shows program version and quit'
complete -c hardinfo2 -s s -l skip-benchmark -d 'Disables all benchmark runs'
complete -c hardinfo2 -s w -l very-verbose -d 'show all details EXAMPLES examples of CLI command usage:'

