# hg-add
# Autogenerated from man page /usr/share/man/man1/hg-add.1.gz
complete -c hg-add -s I -l include -d ' include names matching the given patterns'
complete -c hg-add -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-add -s S -l subrepos -d ' recurse into subrepositories'
complete -c hg-add -s n -l dry-run -d ' do not perform actions, just print output'

