# hg-addremove
# Autogenerated from man page /usr/share/man/man1/hg-addremove.1.gz
complete -c hg-addremove -s s -l similarity -d ' guess renamed files by similarity (0<=s<=100)'
complete -c hg-addremove -s S -l subrepos -d ' recurse into subrepositories'
complete -c hg-addremove -s I -l include -d ' include names matching the given patterns'
complete -c hg-addremove -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-addremove -s n -l dry-run -d ' do not perform actions, just print output'

