# hg-archive
# Autogenerated from man page /usr/share/man/man1/hg-archive.1.gz
complete -c hg-archive -l no-decode -d ' do not pass files through decoders'
complete -c hg-archive -s p -l prefix -d ' directory prefix for files in archive'
complete -c hg-archive -s r -l rev -d ' revision to distribute'
complete -c hg-archive -s t -l type -d ' type of distribution to create'
complete -c hg-archive -s S -l subrepos -d ' recurse into subrepositories'
complete -c hg-archive -s I -l include -d ' include names matching the given patterns'
complete -c hg-archive -s X -l exclude -d ' exclude names matching the given patterns'

