# hg-bundle
# Autogenerated from man page /usr/share/man/man1/hg-bundle.1.gz
complete -c hg-bundle -l exact -d ' compute the base from the revision specified'
complete -c hg-bundle -s f -l force -d ' run even when the destination is unrelated'
complete -c hg-bundle -s r -l rev -d ' a changeset intended to be added to the destination'
complete -c hg-bundle -s b -l branch -d ' a specific branch you would like to bundle'
complete -c hg-bundle -l base -d ' a base changeset assumed to be available at the destination'
complete -c hg-bundle -s a -l all -d ' bundle all changesets in the repository'
complete -c hg-bundle -s t -l type -d ' bundle compression type to use (default: bzip2)'
complete -c hg-bundle -s e -l ssh -d ' specify ssh command to use'
complete -c hg-bundle -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-bundle -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'

