# hg-branches
# Autogenerated from man page /usr/share/man/man1/hg-branches.1.gz
complete -c hg-branches -s a -l active -d ' show only branches that have unmerged heads (DEPRECATED)'
complete -c hg-branches -s c -l closed -d ' show normal and closed branches'
complete -c hg-branches -s r -l rev -d ' show branch name(s) of the given rev'
complete -c hg-branches -s T -l template -d ' display with template'

