# hg-bisect
# Autogenerated from man page /usr/share/man/man1/hg-bisect.1.gz
complete -c hg-bisect -s r -l reset -d ' reset bisect state'
complete -c hg-bisect -s g -l good -d ' mark changeset good'
complete -c hg-bisect -s b -l bad -d ' mark changeset bad'
complete -c hg-bisect -s s -l skip -d ' skip testing changeset'
complete -c hg-bisect -s e -l extend -d ' extend the bisect range'
complete -c hg-bisect -s c -l command -d ' use command to check changeset state'
complete -c hg-bisect -s U -l noupdate -d ' do not update to target'

