# hg-bookmarks
# Autogenerated from man page /usr/share/man/man1/hg-bookmarks.1.gz
complete -c hg-bookmarks -s f -l force -d ' force'
complete -c hg-bookmarks -s r -l rev -d ' revision for bookmark action'
complete -c hg-bookmarks -s d -l delete -d ' delete a given bookmark'
complete -c hg-bookmarks -s m -l rename -d ' rename a given bookmark'
complete -c hg-bookmarks -s i -l inactive -d ' mark a bookmark inactive'
complete -c hg-bookmarks -s l -l list -d ' list existing bookmarks'
complete -c hg-bookmarks -s T -l template -d ' display with template'

