# hg-branch
# Autogenerated from man page /usr/share/man/man1/hg-branch.1.gz
complete -c hg-branch -s f -l force -d ' set branch name even if it shadows an existing branch'
complete -c hg-branch -s C -l clean -d ' reset branch name to parent branch name'
complete -c hg-branch -s r -l rev -d ' change branches of the given revs (EXPERIMENTAL)'

