# hg-backout
# Autogenerated from man page /usr/share/man/man1/hg-backout.1.gz
complete -c hg-backout -l merge -d ' merge with old dirstate parent after backout'
complete -c hg-backout -l commit -d ' commit if no conflicts were encountered (DEPRECATED)'
complete -c hg-backout -l no-commit -d ' do not commit'
complete -c hg-backout -l parent -d ' parent to choose when backing out merge (DEPRECATED)'
complete -c hg-backout -s r -l rev -d ' revision to backout'
complete -c hg-backout -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-backout -s t -l tool -d ' specify merge tool'
complete -c hg-backout -s I -l include -d ' include names matching the given patterns'
complete -c hg-backout -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-backout -s m -l message -d ' use text as commit message'
complete -c hg-backout -s l -l logfile -d ' read commit message from file'
complete -c hg-backout -s d -l date -d ' record the specified date as commit date'
complete -c hg-backout -s u -l user -d ' record the specified user as committer'

