# hg-cat
# Autogenerated from man page /usr/share/man/man1/hg-cat.1.gz
complete -c hg-cat -s o -l output -d ' print output to file with formatted name'
complete -c hg-cat -s r -l rev -d ' print the given revision'
complete -c hg-cat -l decode -d ' apply any matching decode filter'
complete -c hg-cat -s I -l include -d ' include names matching the given patterns'
complete -c hg-cat -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-cat -s T -l template -d ' display with template'

