# hg-commit
# Autogenerated from man page /usr/share/man/man1/hg-commit.1.gz
complete -c hg-commit -s A -l addremove -d ' mark new/missing files as added/removed before committing'
complete -c hg-commit -l close-branch -d ' mark a branch head as closed'
complete -c hg-commit -l amend -d ' amend the parent of the working directory'
complete -c hg-commit -s s -l secret -d ' use the secret phase for committing'
complete -c hg-commit -l draft -d ' use the draft phase for committing'
complete -c hg-commit -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-commit -l force-close-branch -d ' forcibly close branch from a non-head changeset (ADVANCED)'
complete -c hg-commit -s i -l interactive -d ' use interactive mode'
complete -c hg-commit -s I -l include -d ' include names matching the given patterns'
complete -c hg-commit -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-commit -s m -l message -d ' use text as commit message'
complete -c hg-commit -s l -l logfile -d ' read commit message from file'
complete -c hg-commit -s d -l date -d ' record the specified date as commit date'
complete -c hg-commit -s u -l user -d ' record the specified user as committer'
complete -c hg-commit -s S -l subrepos -d ' recurse into subrepositories'

