# hg-config
# Autogenerated from man page /usr/share/man/man1/hg-config.1.gz
complete -c hg-config -s u -l untrusted -d ' show untrusted configuration options'
complete -c hg-config -l exp-all-known -d ' show all known config option (EXPERIMENTAL)'
complete -c hg-config -s e -l edit -d ' edit user config'
complete -c hg-config -s l -l local -d ' edit repository config'
complete -c hg-config -l source -d ' show source of configuration value'
complete -c hg-config -l shared -d ' edit shared source repository config'
complete -c hg-config -l non-shared -d ' edit non shared config'
complete -c hg-config -s g -l global -d ' edit global config'
complete -c hg-config -s T -l template -d ' display with template'

