# hg-clone
# Autogenerated from man page /usr/share/man/man1/hg-clone.1.gz
complete -c hg-clone -s U -l noupdate -d ' the clone will include an empty working directory (only a repository)'
complete -c hg-clone -s u -l updaterev -d ' revision, tag, or branch to check out'
complete -c hg-clone -s r -l rev -d ' do not clone everything, but include this changeset and its ancestors'
complete -c hg-clone -s b -l branch -d ' do not clone everything, but include this branch\'s changesets and their ance…'
complete -c hg-clone -l pull -d ' use pull protocol to copy metadata'
complete -c hg-clone -l uncompressed -d ' an alias to --stream (DEPRECATED)'
complete -c hg-clone -l stream -d ' clone with minimal data processing'
complete -c hg-clone -s e -l ssh -d ' specify ssh command to use'
complete -c hg-clone -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-clone -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'
complete -c hg-clone -o U/--noupdate

