# hg-copy
# Autogenerated from man page /usr/share/man/man1/hg-copy.1.gz
complete -c hg-copy -l forget -d ' unmark a destination file as copied'
complete -c hg-copy -s A -l after -d ' record a copy that has already occurred'
complete -c hg-copy -l at-rev -d ' (un)mark copies in the given revision (EXPERIMENTAL)'
complete -c hg-copy -s f -l force -d ' forcibly copy over an existing managed file'
complete -c hg-copy -s I -l include -d ' include names matching the given patterns'
complete -c hg-copy -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-copy -s n -l dry-run -d ' do not perform actions, just print output'

