# hg-export
# Autogenerated from man page /usr/share/man/man1/hg-export.1.gz
complete -c hg-export -s B -l bookmark -d ' export changes only reachable by given bookmark'
complete -c hg-export -s o -l output -d ' print output to file with formatted name'
complete -c hg-export -l switch-parent -d ' diff against the second parent'
complete -c hg-export -s r -l rev -d ' revisions to export'
complete -c hg-export -s a -l text -d ' treat all files as text'
complete -c hg-export -s g -l git -d ' use git extended diff format (DEFAULT: diff. git)'
complete -c hg-export -l binary -d ' generate binary diffs in git mode (default)'
complete -c hg-export -l nodates -d ' omit dates from diff headers'
complete -c hg-export -s T -l template -d ' display with template'

