# hg-files
# Autogenerated from man page /usr/share/man/man1/hg-files.1.gz
complete -c hg-files -s r -l rev -d ' search the repository as it is in REV'
complete -c hg-files -s 0 -l print0 -d ' end filenames with NUL, for use with xargs'
complete -c hg-files -s I -l include -d ' include names matching the given patterns'
complete -c hg-files -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-files -s T -l template -d ' display with template'
complete -c hg-files -s S -l subrepos -d ' recurse into subrepositories'

