# hg-forget
# Autogenerated from man page /usr/share/man/man1/hg-forget.1.gz
complete -c hg-forget -s i -l interactive -d ' use interactive mode'
complete -c hg-forget -s I -l include -d ' include names matching the given patterns'
complete -c hg-forget -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-forget -s n -l dry-run -d ' do not perform actions, just print output'

