# hg-grep
# Autogenerated from man page /usr/share/man/man1/hg-grep.1.gz
complete -c hg-grep -s 0 -l print0 -d ' end fields with NUL'
complete -c hg-grep -l all -d ' an alias to --diff (DEPRECATED)'
complete -c hg-grep -l diff -d ' search revision differences for when the pattern was added or removed'
complete -c hg-grep -s a -l text -d ' treat all files as text'
complete -c hg-grep -s f -l follow -d ' follow changeset history, or file history across copies and renames'
complete -c hg-grep -s i -l ignore-case -d ' ignore case when matching'
complete -c hg-grep -s l -l files-with-matches -d ' print only filenames and revisions that match'
complete -c hg-grep -s n -l line-number -d ' print matching line numbers'
complete -c hg-grep -s r -l rev -d ' search files changed within revision range'
complete -c hg-grep -l all-files -d ' include all files in the changeset while grepping (DEPRECATED)'
complete -c hg-grep -s u -l user -d ' list the author (long with -v)'
complete -c hg-grep -s d -l date -d ' list the date (short with -q)'
complete -c hg-grep -s T -l template -d ' display with template'
complete -c hg-grep -s I -l include -d ' include names matching the given patterns'
complete -c hg-grep -s X -l exclude -d ' exclude names matching the given patterns'

