# hg-graft
# Autogenerated from man page /usr/share/man/man1/hg-graft.1.gz
complete -c hg-graft -s r -l rev -d ' revisions to graft'
complete -c hg-graft -l base -d ' base revision when doing the graft merge (ADVANCED)'
complete -c hg-graft -l to -d ' graft to this destination, in-memory (EXPERIMENTAL)'
complete -c hg-graft -s c -l continue -d ' resume interrupted graft'
complete -c hg-graft -l stop -d ' stop interrupted graft'
complete -c hg-graft -l abort -d ' abort interrupted graft'
complete -c hg-graft -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-graft -l log -d ' append graft info to log message'
complete -c hg-graft -l no-commit -d ' don\'t commit, just apply the changes in working directory'
complete -c hg-graft -s f -l force -d ' force graft'
complete -c hg-graft -s D -l currentdate -d ' record the current date as commit date'
complete -c hg-graft -s U -l currentuser -d ' record the current user as committer'
complete -c hg-graft -s d -l date -d ' record the specified date as commit date'
complete -c hg-graft -s u -l user -d ' record the specified user as committer'
complete -c hg-graft -s t -l tool -d ' specify merge tool'
complete -c hg-graft -s n -l dry-run -d ' do not perform actions, just print output'
complete -c hg-graft -l keep

