# hg-heads
# Autogenerated from man page /usr/share/man/man1/hg-heads.1.gz
complete -c hg-heads -s r -l rev -d ' show only heads which are descendants of STARTREV'
complete -c hg-heads -s t -l topo -d ' show topological heads only'
complete -c hg-heads -s a -l active -d ' show active branchheads only (DEPRECATED)'
complete -c hg-heads -s c -l closed -d ' show normal and closed branch heads'
complete -c hg-heads -l style -d ' display using template map file (DEPRECATED)'
complete -c hg-heads -s T -l template -d ' display with template'

