# hg-help
# Autogenerated from man page /usr/share/man/man1/hg-help.1.gz
complete -c hg-help -s e -l extension -d ' show only help for extensions'
complete -c hg-help -s c -l command -d ' show only help for commands'
complete -c hg-help -s k -l keyword -d ' show topics matching keyword'
complete -c hg-help -s s -l system -d ' show help for specific platform(s)'

