# hg-import
# Autogenerated from man page /usr/share/man/man1/hg-import.1.gz
complete -c hg-import -s p -l strip -d ' directory strip option for patch'
complete -c hg-import -s b -l base -d ' base path (DEPRECATED)'
complete -c hg-import -l secret -d ' use the secret phase for committing'
complete -c hg-import -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-import -s f -l force -d ' skip check for outstanding uncommitted changes (DEPRECATED)'
complete -c hg-import -l no-commit -d ' don\'t commit, just update the working directory'
complete -c hg-import -l bypass -d ' apply patch without touching the working directory'
complete -c hg-import -l partial -d ' commit even if some hunks fail'
complete -c hg-import -l exact -d ' abort if patch would apply lossily'
complete -c hg-import -l prefix -d ' apply patch to subdirectory'
complete -c hg-import -l import-branch -d ' use any branch information in patch (implied by --exact)'
complete -c hg-import -s m -l message -d ' use text as commit message'
complete -c hg-import -s l -l logfile -d ' read commit message from file'
complete -c hg-import -s d -l date -d ' record the specified date as commit date'
complete -c hg-import -s u -l user -d ' record the specified user as committer'
complete -c hg-import -s s -l similarity -d ' guess renamed files by similarity (0<=s<=100)'

