# hg-init
# Autogenerated from man page /usr/share/man/man1/hg-init.1.gz
complete -c hg-init -s e -l ssh -d ' specify ssh command to use'
complete -c hg-init -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-init -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'

