# hg-identify
# Autogenerated from man page /usr/share/man/man1/hg-identify.1.gz
complete -c hg-identify -s r -l rev -d ' identify the specified revision'
complete -c hg-identify -s n -l num -d ' show local revision number'
complete -c hg-identify -s i -l id -d ' show global revision id'
complete -c hg-identify -s b -l branch -d ' show branch'
complete -c hg-identify -s t -l tags -d ' show tags'
complete -c hg-identify -s B -l bookmarks -d ' show bookmarks'
complete -c hg-identify -s e -l ssh -d ' specify ssh command to use'
complete -c hg-identify -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-identify -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'
complete -c hg-identify -s T -l template -d ' display with template'

