# hg-locate
# Autogenerated from man page /usr/share/man/man1/hg-locate.1.gz
complete -c hg-locate -s r -l rev -d ' search the repository as it is in REV'
complete -c hg-locate -s 0 -l print0 -d ' end filenames with NUL, for use with xargs'
complete -c hg-locate -s f -l fullpath -d ' print complete paths from the filesystem root'
complete -c hg-locate -s I -l include -d ' include names matching the given patterns'
complete -c hg-locate -s X -l exclude -d ' exclude names matching the given patterns'

