# hg-manifest
# Autogenerated from man page /usr/share/man/man1/hg-manifest.1.gz
complete -c hg-manifest -s r -l rev -d ' revision to display'
complete -c hg-manifest -l all -d ' list files from all revisions'
complete -c hg-manifest -s T -l template -d ' display with template'

