# hg-merge
# Autogenerated from man page /usr/share/man/man1/hg-merge.1.gz
complete -c hg-merge -s f -l force -d ' force a merge including outstanding changes (DEPRECATED)'
complete -c hg-merge -s r -l rev -d ' revision to merge'
complete -c hg-merge -s P -l preview -d ' review revisions to merge (no merge is performed)'
complete -c hg-merge -l abort -d ' abort the ongoing merge'
complete -c hg-merge -s t -l tool -d ' specify merge tool'

