# hg-phase
# Autogenerated from man page /usr/share/man/man1/hg-phase.1.gz
complete -c hg-phase -s p -l public -d ' set changeset phase to public'
complete -c hg-phase -s d -l draft -d ' set changeset phase to draft'
complete -c hg-phase -s s -l secret -d ' set changeset phase to secret'
complete -c hg-phase -s f -l force -d ' allow to move boundary backward'
complete -c hg-phase -s r -l rev -d ' target revision'

