# hg-purge
# Autogenerated from man page /usr/share/man/man1/hg-purge.1.gz
complete -c hg-purge -s a -l abort-on-err -d ' abort if an error occurs'
complete -c hg-purge -l all -d ' purge ignored files too'
complete -c hg-purge -s i -l ignored -d ' purge only ignored files'
complete -c hg-purge -l dirs -d ' purge empty directories'
complete -c hg-purge -l files -d ' purge files'
complete -c hg-purge -s p -l print -d ' print filenames instead of deleting them'
complete -c hg-purge -s 0 -l print0 -d ' end filenames with NUL, for use with xargs (implies -p/--print)'
complete -c hg-purge -l confirm -d ' ask before permanently deleting files'
complete -c hg-purge -s I -l include -d ' include names matching the given patterns'
complete -c hg-purge -s X -l exclude -d ' exclude names matching the given patterns'

