# hg-pull
# Autogenerated from man page /usr/share/man/man1/hg-pull.1.gz
complete -c hg-pull -s u -l update -d ' update to new branch head if new descendants were pulled'
complete -c hg-pull -s f -l force -d ' run even when remote repository is unrelated'
complete -c hg-pull -l confirm -d ' confirm pull before applying changes'
complete -c hg-pull -s r -l rev -d ' a remote changeset intended to be added'
complete -c hg-pull -s B -l bookmark -d ' bookmark to pull'
complete -c hg-pull -s b -l branch -d ' a specific branch you would like to pull'
complete -c hg-pull -l remote-hidden -d ' include changesets hidden on the remote (EXPERIMENTAL)'
complete -c hg-pull -s e -l ssh -d ' specify ssh command to use'
complete -c hg-pull -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-pull -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'
complete -c hg-pull -s R -d 'project in the working directory'

