# hg-parents
# Autogenerated from man page /usr/share/man/man1/hg-parents.1.gz
complete -c hg-parents -s r -l rev -d ' show parents of the specified revision'
complete -c hg-parents -l style -d ' display using template map file (DEPRECATED)'
complete -c hg-parents -s T -l template -d ' display with template'

