# hg-push
# Autogenerated from man page /usr/share/man/man1/hg-push.1.gz
complete -c hg-push -s f -l force -d ' force push'
complete -c hg-push -s r -l rev -d ' a changeset intended to be included in the destination'
complete -c hg-push -s B -l bookmark -d ' bookmark to push'
complete -c hg-push -l all-bookmarks -d ' push all bookmarks (EXPERIMENTAL)'
complete -c hg-push -s b -l branch -d ' a specific branch you would like to push'
complete -c hg-push -l new-branch -d ' allow pushing a new branch'
complete -c hg-push -l pushvars -d ' variables that can be sent to server (ADVANCED)'
complete -c hg-push -l publish -d ' push the changeset as public (EXPERIMENTAL)'
complete -c hg-push -s e -l ssh -d ' specify ssh command to use'
complete -c hg-push -l remotecmd -d ' specify hg command to run on the remote side'
complete -c hg-push -l insecure -d ' do not verify server certificate (ignoring web. cacerts config)'

