# hg-resolve
# Autogenerated from man page /usr/share/man/man1/hg-resolve.1.gz
complete -c hg-resolve -s a -l all -d ' select all unresolved files'
complete -c hg-resolve -s l -l list -d ' list state of files needing merge'
complete -c hg-resolve -s m -l mark -d ' mark files as resolved'
complete -c hg-resolve -s u -l unmark -d ' mark files as unresolved'
complete -c hg-resolve -s n -l no-status -d ' hide status prefix'
complete -c hg-resolve -l re-merge -d ' re-merge files'
complete -c hg-resolve -s t -l tool -d ' specify merge tool'
complete -c hg-resolve -s I -l include -d ' include names matching the given patterns'
complete -c hg-resolve -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-resolve -s T -l template -d ' display with template'

