# hg-revert
# Autogenerated from man page /usr/share/man/man1/hg-revert.1.gz
complete -c hg-revert -s a -l all -d ' revert all changes when no arguments given'
complete -c hg-revert -s d -l date -d ' tipmost revision matching date'
complete -c hg-revert -s r -l rev -d ' revert to the specified revision'
complete -c hg-revert -s C -l no-backup -d ' do not save backup copies of files'
complete -c hg-revert -s i -l interactive -d ' interactively select the changes'
complete -c hg-revert -s I -l include -d ' include names matching the given patterns'
complete -c hg-revert -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-revert -s n -l dry-run -d ' do not perform actions, just print output'

