# hg-remove
# Autogenerated from man page /usr/share/man/man1/hg-remove.1.gz
complete -c hg-remove -s A -l after -d ' record delete for missing files'
complete -c hg-remove -s f -l force -d ' forget added files, delete modified files'
complete -c hg-remove -s S -l subrepos -d ' recurse into subrepositories'
complete -c hg-remove -s I -l include -d ' include names matching the given patterns'
complete -c hg-remove -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-remove -s n -l dry-run -d ' do not perform actions, just print output'
complete -c hg-remove -o A/--after -d 'been deleted, -f/--force can be used to force deletion, and -Af can be used t…'
complete -c hg-remove -o Af -d 'T}	T{ R T}	T{ R T}	T{ R T}	T{ R T} _'

