# hg-rollback
# Autogenerated from man page /usr/share/man/man1/hg-rollback.1.gz
complete -c hg-rollback -s n -l dry-run -d ' do not perform actions, just print output'
complete -c hg-rollback -s f -l force -d ' ignore safety measures'

