# hg-rename
# Autogenerated from man page /usr/share/man/man1/hg-rename.1.gz
complete -c hg-rename -l forget -d ' unmark a destination file as renamed'
complete -c hg-rename -s A -l after -d ' record a rename that has already occurred'
complete -c hg-rename -l at-rev -d ' (un)mark renames in the given revision (EXPERIMENTAL)'
complete -c hg-rename -s f -l force -d ' forcibly move over an existing managed file'
complete -c hg-rename -s I -l include -d ' include names matching the given patterns'
complete -c hg-rename -s X -l exclude -d ' exclude names matching the given patterns'
complete -c hg-rename -s n -l dry-run -d ' do not perform actions, just print output'

