# hg-shelve
# Autogenerated from man page /usr/share/man/man1/hg-shelve.1.gz
complete -c hg-shelve -s A -l addremove -d ' mark new/missing files as added/removed before shelving'
complete -c hg-shelve -s u -l unknown -d ' store unknown files in the shelve'
complete -c hg-shelve -l cleanup -d ' delete all shelved changes'
complete -c hg-shelve -l date -d ' shelve with the specified commit date'
complete -c hg-shelve -s d -l delete -d ' delete the named shelved change(s)'
complete -c hg-shelve -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-shelve -s k -l keep -d ' shelve, but keep changes in the working directory'
complete -c hg-shelve -s l -l list -d ' list current shelves'
complete -c hg-shelve -s m -l message -d ' use text as shelve message'
complete -c hg-shelve -s n -l name -d ' use the given name for the shelved commit'
complete -c hg-shelve -s p -l patch -d ' output patches for changes (provide the names of the shelved changes as posi…'
complete -c hg-shelve -s i -l interactive -d ' interactive mode'
complete -c hg-shelve -l stat -d ' output diffstat-style summary of changes (provide the names of the shelved c…'
complete -c hg-shelve -s I -l include -d ' include names matching the given patterns'
complete -c hg-shelve -s X -l exclude -d ' exclude names matching the given patterns'

