# hg-tag
# Autogenerated from man page /usr/share/man/man1/hg-tag.1.gz
complete -c hg-tag -s f -l force -d ' force tag'
complete -c hg-tag -s l -l local -d ' make the tag local'
complete -c hg-tag -s r -l rev -d ' revision to tag'
complete -c hg-tag -l remove -d ' remove a tag'
complete -c hg-tag -s e -l edit -d ' invoke editor on commit messages'
complete -c hg-tag -s m -l message -d ' use text as commit message'
complete -c hg-tag -s d -l date -d ' record the specified date as commit date'
complete -c hg-tag -s u -l user -d ' record the specified user as committer'
complete -c hg-tag -o f/--force -d changeset

