# hg-tip
# Autogenerated from man page /usr/share/man/man1/hg-tip.1.gz
complete -c hg-tip -s p -l patch -d ' show patch'
complete -c hg-tip -s g -l git -d ' use git extended diff format'
complete -c hg-tip -l style -d ' display using template map file (DEPRECATED)'
complete -c hg-tip -s T -l template -d ' display with template'

