# hg-update
# Autogenerated from man page /usr/share/man/man1/hg-update.1.gz
complete -c hg-update -s C -l clean -d ' discard uncommitted changes (no backup)'
complete -c hg-update -s c -l check -d ' require clean working directory'
complete -c hg-update -s m -l merge -d ' merge uncommitted changes'
complete -c hg-update -s d -l date -d ' tipmost revision matching date'
complete -c hg-update -s r -l rev -d ' revision'
complete -c hg-update -s t -l tool -d ' specify merge tool'

