# hg-unshelve
# Autogenerated from man page /usr/share/man/man1/hg-unshelve.1.gz
complete -c hg-unshelve -s a -l abort -d ' abort an incomplete unshelve operation'
complete -c hg-unshelve -s c -l continue -d ' continue an incomplete unshelve operation'
complete -c hg-unshelve -s i -l interactive -d ' use interactive mode (EXPERIMENTAL)'
complete -c hg-unshelve -s k -l keep -d ' keep shelve after unshelving'
complete -c hg-unshelve -s n -l name -d ' restore shelved change with given name'
complete -c hg-unshelve -s t -l tool -d ' specify merge tool'
complete -c hg-unshelve -l date -d ' set date for temporary commits (DEPRECATED)'

