# libinput-list-devices
# Autogenerated from man page /usr/share/man/man1/libinput-list-devices.1.gz
complete -c libinput-list-devices -l help -d 'Print help'
complete -c libinput-list-devices -l verbose -d 'Use verbose output NOTES'

