# lvmdevices
# Autogenerated from man page /usr/share/man/man8/lvmdevices.8.gz
complete -c lvmdevices -l addev -l deviceidtype -d 'device it will be used, otherwise the device will be added using the type tha…'

