# makechrootpkg
# Autogenerated from man page /usr/share/man/man1/makechrootpkg.1.gz
complete -c makechrootpkg -s h
complete -c makechrootpkg -s c
complete -c makechrootpkg -s d
complete -c makechrootpkg -s D
complete -c makechrootpkg -s t
complete -c makechrootpkg -s u
complete -c makechrootpkg -s r
complete -c makechrootpkg -s I
complete -c makechrootpkg -s l
complete -c makechrootpkg -s n
complete -c makechrootpkg -s C
complete -c makechrootpkg -s T
complete -c makechrootpkg -s U
complete -c makechrootpkg -s x

