# makerepropkg
# Autogenerated from man page /usr/share/man/man1/makerepropkg.1.gz
complete -c makerepropkg -s d
complete -c makerepropkg -s n
complete -c makerepropkg -s c
complete -c makerepropkg -s M
complete -c makerepropkg -s l
complete -c makerepropkg -s h

