# mkarchroot
# Autogenerated from man page /usr/share/man/man1/mkarchroot.1.gz
complete -c mkarchroot -s U
complete -c mkarchroot -s C
complete -c mkarchroot -s M
complete -c mkarchroot -s c
complete -c mkarchroot -s f
complete -c mkarchroot -s s
complete -c mkarchroot -s h

