# namcap
# Autogenerated from man page /usr/share/man/man1/namcap.1.gz
complete -c namcap -s e -l exclude -d 'Do not run RULELIST rules on the package'
complete -c namcap -s i -l info -d 'display information messages'
complete -c namcap -s L -l list -d 'return a list of valid rules and their descriptions'
complete -c namcap -s m -l machine-readable -d 'displays easily parseable namcap tags instead of the normal human readable de…'
complete -c namcap -s r -l rules -d 'only apply RULELIST rules to the package'
complete -c namcap -s v -l version -d 'print version and exit RULES'

