# nvme-ocp-unsupported-reqs-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-unsupported-reqs-log.1.gz
complete -c nvme-ocp-unsupported-reqs-log -s o -l output-format -d 'This option will set the reporting format to normal, json, or binary'

