# nvme-dapustor-smart-log-add
# Autogenerated from man page /usr/share/man/man1/nvme-dapustor-smart-log-add.1.gz
complete -c nvme-dapustor-smart-log-add -s n -l namespace-id -d 'Retrieve the Additional SMART log for the given nsid'
complete -c nvme-dapustor-smart-log-add -s b -l raw-binary -d 'Print the raw DapuStor Additional SMART log buffer to stdout'
complete -c nvme-dapustor-smart-log-add -s j -l json -d 'Dump output in json format'

