# nvme-ocp-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-internal-log.1.gz
complete -c nvme-ocp-internal-log -s l -l telemetry-log -d 'File name to existing Telemetry Host-Initiated raw binary data to be used'
complete -c nvme-ocp-internal-log -s s -l string-log -d 'File name to existing OCP String Log raw binary data to be used'
complete -c nvme-ocp-internal-log -s o -l output-file -d 'Filepath name to where human-readable output data will be saved to'
complete -c nvme-ocp-internal-log -s f -l output-format -d 'Set the reporting format to normal, json'
complete -c nvme-ocp-internal-log -s a -l data-area -d 'Retrieves the specific data area requested.  Valid inputs are 1,2'
complete -c nvme-ocp-internal-log -s t -l telemetry-type -d 'Set the telemetry type to host, host0, host1 or controller'

