# nvme-solidigm-garbage-collect-log
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-garbage-collect-log.1.gz
complete -c nvme-solidigm-garbage-collect-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

