# nvme-ocp-get-plp-health-check-interval
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-get-plp-health-check-interval.1.gz
complete -c nvme-ocp-get-plp-health-check-interval -s s -l sel -d 'Select (SEL): This field specifies which value of the attributes to return in…'

