# nvme-sndk-vs-device-waf
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-vs-device-waf.1.gz
complete -c nvme-sndk-vs-device-waf -s o -l output-format -d 'Set the reporting format to normal, or json'
complete -c nvme-sndk-vs-device-waf -s n -l namespace-id -d 'Sets the command\'s nsid value to the given nsid'

