# nvme-effects-log
# Autogenerated from man page /usr/share/man/man1/nvme-effects-log.1.gz
complete -c nvme-effects-log -s H -l human-readable -d 'This option will parse and format many of the bit fields into a human-readabl…'
complete -c nvme-effects-log -s b -l raw-binary -d 'This option will print the raw buffer to stdout'
complete -c nvme-effects-log -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-effects-log -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-effects-log -s t -l timeout -d 'Override default timeout value.  In milliseconds'

