# nvme-supported-log-pages
# Autogenerated from man page /usr/share/man/man1/nvme-supported-log-pages.1.gz
complete -c nvme-supported-log-pages -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-supported-log-pages -s v -l verbose -d 'Increase the information detail in the output'

