# nvme-solidigm-log-page-directory
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-log-page-directory.1.gz
complete -c nvme-solidigm-log-page-directory -s o -l output-format -d 'Set the reporting format to normal or json'

