# nvme-get-property
# Autogenerated from man page /usr/share/man/man1/nvme-get-property.1.gz
complete -c nvme-get-property -s O -l offset -d 'The offset of the property'
complete -c nvme-get-property -s H -d '--human-readable: Show the fields packed in the property'
complete -c nvme-get-property -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-get-property -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-get-property -s t -l timeout -d 'Override default timeout value.  In milliseconds'
complete -c nvme-get-property -l human-readable

