# nvme-ocp-set-telemetry-profile
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-set-telemetry-profile.1.gz
complete -c nvme-ocp-set-telemetry-profile -s t -l tps -d 'Telemetry Profile Select'

