# nvme-disconnect
# Autogenerated from man page /usr/share/man/man1/nvme-disconnect.1.gz
complete -c nvme-disconnect -s n -l nqn -d 'Indicates that all controllers for the NVMe subsystems specified should be re…'
complete -c nvme-disconnect -s d -l device -d 'Indicates that the controller with the specified name should be removed'
complete -c nvme-disconnect -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-disconnect -s v -l verbose -d 'Increase the information detail in the output'

