# nvme-set-property
# Autogenerated from man page /usr/share/man/man1/nvme-set-property.1.gz
complete -c nvme-set-property -s O -l offset -d 'The offset of the property'
complete -c nvme-set-property -s V -l value -d 'The value of the property to be set'
complete -c nvme-set-property -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-set-property -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-set-property -s t -l timeout -d 'Override default timeout value.  In milliseconds'

