# nvme-capacity-mgmt
# Autogenerated from man page /usr/share/man/man1/nvme-capacity-mgmt.1.gz
complete -c nvme-capacity-mgmt -s O -l operation -d 'Operation to be performed by the controller'
complete -c nvme-capacity-mgmt -s i -l element-id -d 'Value specific to the value of the Operation field'
complete -c nvme-capacity-mgmt -s l -l cap-lower -d 'Least significant 32 bits of the capacity in bytes of the Endurance Group or …'
complete -c nvme-capacity-mgmt -s u -l cap-upper -d 'Most significant 32 bits of the capacity in bytes of the Endurance Group or N…'
complete -c nvme-capacity-mgmt -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-capacity-mgmt -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-capacity-mgmt -s t -l timeout -d 'Override default timeout value.  In milliseconds'

