# nvme-io-mgmt-send
# Autogenerated from man page /usr/share/man/man1/nvme-io-mgmt-send.1.gz
complete -c nvme-io-mgmt-send -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-io-mgmt-send -s d -l data -d 'File to read payload from'
complete -c nvme-io-mgmt-send -s l -l data-len -d 'Payload data buffer length'
complete -c nvme-io-mgmt-send -s m -l mo -d 'Management Operation to perform'
complete -c nvme-io-mgmt-send -s s -l mos -d 'Management Operation Specific parameter'
complete -c nvme-io-mgmt-send -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-io-mgmt-send -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-io-mgmt-send -s t -l timeout -d 'Override default timeout value.  In milliseconds'

