# nvme-lockdown
# Autogenerated from man page /usr/share/man/man1/nvme-lockdown.1.gz
complete -c nvme-lockdown -s O -l ofi -d 'Opcode or Feature Identifier(OFI) specifies the command opcode or Set Feature…'
complete -c nvme-lockdown -s f -l ifc -d 'Interface (INF) field identifies the interfaces affected by this command'
complete -c nvme-lockdown -s p -l prhbt -d 'Prohibit (PRHBT) bit specifies whether to prohibit or allow the command opcod…'
complete -c nvme-lockdown -s s -l scp -d 'Scope (SCP) field specifies the contents of the Opcode or Feature Identifier …'
complete -c nvme-lockdown -s U -l uuid -d 'UUID Index - If this field is set to a non-zero value, then the value of this…'
complete -c nvme-lockdown -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-lockdown -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-lockdown -s t -l timeout -d 'Override default timeout value.  In milliseconds'

