# nvme-sndk-vs-smart-add-log
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-vs-smart-add-log.1.gz
complete -c nvme-sndk-vs-smart-add-log -s i -l interval -d 'Return the statistics from specific interval, defaults to 14'
complete -c nvme-sndk-vs-smart-add-log -s o -l output-format -d 'Set the reporting format to normal, or json'
complete -c nvme-sndk-vs-smart-add-log -s l -l log-page-version -d 'Log Page Version: 0 = vendor, 1 = sndk'
complete -c nvme-sndk-vs-smart-add-log -s p -l log-page-mask -d 'Supply a comma separated list of desired log pages to display'
complete -c nvme-sndk-vs-smart-add-log -s n -l namespace-id -d 'Sets the command\'s nsid value to the given nsid'

