# nvme-sed-discover
# Autogenerated from man page /usr/share/man/man1/nvme-sed-discover.1.gz
complete -c nvme-sed-discover -s v -l verbose -d 'Print extended feature discovery information'
complete -c nvme-sed-discover -s u -l udev -d 'Print locking information in form suitable for udev rules'

