# nvme-list-subsys
# Autogenerated from man page /usr/share/man/man1/nvme-list-subsys.1.gz
complete -c nvme-list-subsys -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-list-subsys -s v -l verbose -d 'Increase the information detail in the output'

