# nvme-sndk-get-latency-monitor-log
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-get-latency-monitor-log.1.gz
complete -c nvme-sndk-get-latency-monitor-log -s o -l output-format -d 'Set the reporting format to normal or json'

