# nvme-sed-lock
# Autogenerated from man page /usr/share/man/man1/nvme-sed-lock.1.gz
complete -c nvme-sed-lock -s r -l read-only -d 'Set locking range to read-only'
complete -c nvme-sed-lock -s k -l ask-key -d 'Prompt for SED authentication key'

