# nvme-gen-hostnqn
# Autogenerated from man page /usr/share/man/man1/nvme-gen-hostnqn.1.gz
complete -c nvme-gen-hostnqn -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-gen-hostnqn -s v -l verbose -d 'Increase the information detail in the output'

