# nvme-sndk-get-dev-capabilities-log
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-get-dev-capabilities-log.1.gz
complete -c nvme-sndk-get-dev-capabilities-log -s o -l output-format -d 'Set the reporting format to normal, or json'

