# nvme-list-ctrl
# Autogenerated from man page /usr/share/man/man1/nvme-list-ctrl.1.gz
complete -c nvme-list-ctrl -s c -l cntid -d 'Retrieve the identify list structure starting with the given controller id'
complete -c nvme-list-ctrl -s n -l namespace-id -d 'If provided, will request the controllers attached to the specified namespace'
complete -c nvme-list-ctrl -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-list-ctrl -s v -l verbose -d 'Increase the information detail in the output'

