# nvme-flush
# Autogenerated from man page /usr/share/man/man1/nvme-flush.1.gz
complete -c nvme-flush -s n -l namespace-id -d 'Specify the optional namespace id for this command'
complete -c nvme-flush -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-flush -s v -l verbose -d 'Increase the information detail in the output'

