# nvme-ocp-device-capability-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-device-capability-log.1.gz
complete -c nvme-ocp-device-capability-log -s o -l output-format -d 'Set the reporting format to normal or json or binary'

