# nvme-telemetry-log
# Autogenerated from man page /usr/share/man/man1/nvme-telemetry-log.1.gz
complete -c nvme-telemetry-log -s O -l output-file -d 'File name to which raw binary data will be saved to'
complete -c nvme-telemetry-log -s g -l host-generate -d 'If set to 1, controller shall capture the Telemetry Host-Initiated data repre…'
complete -c nvme-telemetry-log -s d -l data-area -d 'Retrieves the specific data area requested.  Valid inputs are 1,2,3,4'
complete -c nvme-telemetry-log -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-telemetry-log -s v -l verbose -d 'Increase the information detail in the output'

