# nvme-sanitize
# Autogenerated from man page /usr/share/man/man1/nvme-sanitize.1.gz
complete -c nvme-sanitize -s d -l no-dealloc -d 'No Deallocate After Sanitize: If set, then the controller shall not deallocat…'
complete -c nvme-sanitize -s i -l oipbp -d 'Overwrite Invert Pattern Between Passes: If set, then the Overwrite Pattern s…'
complete -c nvme-sanitize -s n -l owpass -d 'Overwrite Pass Count: This field specifies the number of overwrite passes (i'
complete -c nvme-sanitize -s u -l ause -d 'Allow Unrestricted Sanitize Exit: If set, then the sanitize operation is perf…'
complete -c nvme-sanitize -s a -l sanact -d 'Sanitize Action: '
complete -c nvme-sanitize -s p -l ovrpat -d 'Overwrite Pattern: This field is ignored unless the Sanitize Action field in …'
complete -c nvme-sanitize -s e -l emvs -d 'Enter Media Verification State: If set, then the Media Verification state sha…'
complete -c nvme-sanitize -l force -d 'Ignore namespace is currently busy and performed the operation even though'
complete -c nvme-sanitize -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-sanitize -s v -l verbose -d 'Increase the information detail in the output'

