# nvme-ns-rescan
# Autogenerated from man page /usr/share/man/man1/nvme-ns-rescan.1.gz
complete -c nvme-ns-rescan -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-ns-rescan -s v -l verbose -d 'Increase the information detail in the output'

