# nvme-fdp-feature
# Autogenerated from man page /usr/share/man/man1/nvme-fdp-feature.1.gz
complete -c nvme-fdp-feature -s e -l endgrp-id -d 'Specify the endurance group ID'
complete -c nvme-fdp-feature -s c -l enable-conf-idx -d 'Enable FDP feature with the specified configuration'
complete -c nvme-fdp-feature -s d -l disable -d 'Disable the current FDP feature configuration'
complete -c nvme-fdp-feature -s v -l verbose -d 'Increase verbosity of the output'

