# nvme-solidigm-clear-pcie-correctable-errors
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-clear-pcie-correctable-errors.1.gz
complete -c nvme-solidigm-clear-pcie-correctable-errors -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'

