# nvme-solidigm-workload-tracker
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-workload-tracker.1.gz
complete -c nvme-solidigm-workload-tracker -s U -l uuid-index -d 'Specify the UUID index (0-127) for the command'
complete -c nvme-solidigm-workload-tracker -s e -l enable -d 'Enable the workload tracker before capturing samples'
complete -c nvme-solidigm-workload-tracker -s d -l disable -d 'Disable the workload tracker after capturing samples'
complete -c nvme-solidigm-workload-tracker -s s -l sample-time -d 'Set the sample interval'
complete -c nvme-solidigm-workload-tracker -s t -l type -d 'Set the tracker type'
complete -c nvme-solidigm-workload-tracker -s r -l run-time -d 'Limit runtime capture time in seconds'
complete -c nvme-solidigm-workload-tracker -s f -l flush-freq -d 'Number of samples (1 to 126) to wait before extracting data'
complete -c nvme-solidigm-workload-tracker -s w -l wall-clock -d 'Log current wall timestamp when entry was retrieved'
complete -c nvme-solidigm-workload-tracker -s T -l trigger-field -d 'Field name to stop trigger on'
complete -c nvme-solidigm-workload-tracker -s V -l trigger-threshold -d 'Field value to trigger stop sampling'
complete -c nvme-solidigm-workload-tracker -s D -l trigger-on-delta -d 'Trigger on delta to stop sampling'
complete -c nvme-solidigm-workload-tracker -s L -l trigger-on-latency -d 'Use latency tracker to trigger stop sampling'
complete -c nvme-solidigm-workload-tracker -s v -l verbose -d 'Increase logging verbosity.  Can be used multiple times'

