# nvme-ocp-smart-add-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-smart-add-log.1.gz
complete -c nvme-ocp-smart-add-log -s o -l output-format -d 'Set the reporting format to normal or json'
complete -c nvme-ocp-smart-add-log -l output-format-version -d 'Set the field labels in the reporting format to either 1 (the original) or 2'

