# nvme-ocp-telemetry-string-log-page
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-telemetry-string-log-page.1.gz
complete -c nvme-ocp-telemetry-string-log-page -s o -l output-format -d 'This option will set the reporting format to normal, json, or binary'

