# nvme-solidigm-vs-fw-activate-history
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-vs-fw-activate-history.1.gz
complete -c nvme-solidigm-vs-fw-activate-history -s o -l output-format -d 'Set the reporting format to normal or json'

