# nvme-sndk-vs-pcie-stats
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-vs-pcie-stats.1.gz
complete -c nvme-sndk-vs-pcie-stats -s o -l output-format -d 'Set the reporting format to normal, or json'

