# nvme-ocp-get-dssd-async-event-config
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-get-dssd-async-event-config.1.gz
complete -c nvme-ocp-get-dssd-async-event-config -s s -l sel -d 'Select (SEL): This field specifies which value of the attributes to return in…'

