# nvme-dir-send
# Autogenerated from man page /usr/share/man/man1/nvme-dir-send.1.gz
complete -c nvme-dir-send -s n -l namespace-id -d 'Retrieve the feature for the given nsid'
complete -c nvme-dir-send -s D -l dir-type -d 'Directive type'
complete -c nvme-dir-send -s S -l dir-spec -d 'Directive specific'
complete -c nvme-dir-send -s O -l dir-oper -d 'Directive operation'
complete -c nvme-dir-send -s T -l target-dir -d 'Target directive of the operation'
complete -c nvme-dir-send -s e -l endir -d 'Target directive enable(1) or disable (0) operation '
complete -c nvme-dir-send -s l -l data-len -d 'The data length for the buffer returned for this feature'
complete -c nvme-dir-send -s b -l raw-binary -d 'Print the raw receive buffer to stdout if the command returns a structure'
complete -c nvme-dir-send -s H -l human-readable -d 'deprecated; does nothing so use the --verbose flag instead'
complete -c nvme-dir-send -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-dir-send -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-dir-send -s t -l timeout -d 'Override default timeout value.  In milliseconds'

