# nvme-sndk-set-latency-monitor-feature
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-set-latency-monitor-feature.1.gz
complete -c nvme-sndk-set-latency-monitor-feature -s t -l active_bucket_timer_threshold -d 'The value that loads the Active Bucket Timer Threshold; default value is 07E0h'
complete -c nvme-sndk-set-latency-monitor-feature -s a -l active_threshold_a -d 'The value that loads into the Active Threshold A; default value is 05h'
complete -c nvme-sndk-set-latency-monitor-feature -s b -l active_threshold_b -d 'The value that loads into the Active Threshold B; default value is 13h'
complete -c nvme-sndk-set-latency-monitor-feature -s c -l active_threshold_c -d 'The value that loads into the Active Threshold C; default value is 1Eh'
complete -c nvme-sndk-set-latency-monitor-feature -s d -l active_threshold_d -d 'The value that loads into the Active Threshold D; default value is 2Eh'
complete -c nvme-sndk-set-latency-monitor-feature -s f -l active_latency_config -d 'The value that loads into the Active Latency Configuration'
complete -c nvme-sndk-set-latency-monitor-feature -s w -l active_latency_minimum_window -d 'The value that loads into the Active Latency Minimum Window; default value is…'
complete -c nvme-sndk-set-latency-monitor-feature -s r -l debug_log_trigger_enable -d 'The value that loads into the Debug Log Trigger Enable; When set to 1b the fi…'
complete -c nvme-sndk-set-latency-monitor-feature -s l -l discard_debug_log -d 'Discard Debug Log'
complete -c nvme-sndk-set-latency-monitor-feature -s e -l latency_monitor_feature_enable -d 'Latency Monitor Feature Enable; When set to 01h the Latency Monitor Feature i…'

