# nvme-tls-key
# Autogenerated from man page /usr/share/man/man1/nvme-tls-key.1.gz
complete -c nvme-tls-key -s k -l keyring -d 'Name of the keyring into which the retained TLS key should be stored'
complete -c nvme-tls-key -s t -l keytype -d 'Type of the key for resulting TLS key.  Default is psk'
complete -c nvme-tls-key -s f -l keyfile -d 'File to read the keys from or write the keys to instead of stdin / stdout'
complete -c nvme-tls-key -s i -l import -d 'Read the key data from the file specified by --keyfile or stdin if not present'
complete -c nvme-tls-key -s e -l export -d 'Write the key data to the file specified by --keyfile or stdout if not present'
complete -c nvme-tls-key -s r -l revoke -d 'Revoke a key from a keyring'
complete -c nvme-tls-key -s v -l verbose -d 'Increase the information detail in the output'

