# nvme-solidigm-vs-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-vs-internal-log.1.gz
complete -c nvme-solidigm-vs-internal-log -s t -l log-type -d 'Specify the type of log to retrieve'
complete -c nvme-solidigm-vs-internal-log -s d -l output-dir -d 'Specify the output directory for the log files'
complete -c nvme-solidigm-vs-internal-log -s v -l verbose -d 'Enable verbose output for additional information during the log retrieval pro…'

