# nvme-sed-revert
# Autogenerated from man page /usr/share/man/man1/nvme-sed-revert.1.gz
complete -c nvme-sed-revert -s e -l destructive -d 'Revert drive destructively (data erased)'
complete -c nvme-sed-revert -s p -l psid -d 'Destructively revert drive using its PSID'

