# nvme-reset
# Autogenerated from man page /usr/share/man/man1/nvme-reset.1.gz
complete -c nvme-reset -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-reset -s v -l verbose -d 'Increase the information detail in the output'

