# nvme-detach-ns
# Autogenerated from man page /usr/share/man/man1/nvme-detach-ns.1.gz
complete -c nvme-detach-ns -s n -l namespace-id -d 'The namespace identifier to detach'
complete -c nvme-detach-ns -s c -l controllers -d 'The comma separated list of controller identifiers to detach the namespace fr…'
complete -c nvme-detach-ns -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-detach-ns -s v -l verbose -d 'Increase the information detail in the output'

