# nvme-ocp-get-dssd-power-state-feature
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-get-dssd-power-state-feature.1.gz
complete -c nvme-ocp-get-dssd-power-state-feature -s S -l sel -d 'Select (SEL): This field specifies which value of the attributes to return in…'
complete -c nvme-ocp-get-dssd-power-state-feature -s a -l all -d 'Print out all 3 values at once - Current DSSD Power State, Default DSSD Power…'
complete -c nvme-ocp-get-dssd-power-state-feature -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'

