# nvme-ocp-set-plp-health-check-interval
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-set-plp-health-check-interval.1.gz
complete -c nvme-ocp-set-plp-health-check-interval -s p -l plp_health_interval -d 'Set the plp health check interval [31:16]'
complete -c nvme-ocp-set-plp-health-check-interval -s n -l no-uuid -d 'Do not try to automatically detect UUID index for this command (required for …'
complete -c nvme-ocp-set-plp-health-check-interval -s s -l save -d 'Save the attribute so that it persists through all power states and resets'

