# nvme-sndk-vs-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-vs-internal-log.1.gz
complete -c nvme-sndk-vs-internal-log -s o -l output-file -d 'Output file; defaults to device serial number followed by "internal_fw_log<da…'
complete -c nvme-sndk-vs-internal-log -s s -l transfer-size -d 'Transfer size; defaults to 0x10000 (65536 decimal) bytes'
complete -c nvme-sndk-vs-internal-log -s d -l data-area -d 'DUI data area to retrieve'
complete -c nvme-sndk-vs-internal-log -s f -l file-size -d 'Specifies the desired size of the data file starting at the passed in offset'
complete -c nvme-sndk-vs-internal-log -s e -l offset -d 'Specifies the data offset at which to start retrieving the data'
complete -c nvme-sndk-vs-internal-log -s t -l type -d 'Specifies the telemetry type - NONE, HOST, or CONTROLLER'
complete -c nvme-sndk-vs-internal-log -s v -l verbose -d 'Provides additional debug messages for certain drives'

