# nvme-attach-ns
# Autogenerated from man page /usr/share/man/man1/nvme-attach-ns.1.gz
complete -c nvme-attach-ns -s n -l namespace-id -d 'The namespace identifier to attach but not attached already'
complete -c nvme-attach-ns -s c -o controllers -d 'The comma separated list of controller identifiers to attach the namespace too'
complete -c nvme-attach-ns -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-attach-ns -s v -l verbose -d 'Increase the information detail in the output'

