# nvme-delete-ns
# Autogenerated from man page /usr/share/man/man1/nvme-delete-ns.1.gz
complete -c nvme-delete-ns -s n -l namespace-id -d 'The namespace identifier to delete'
complete -c nvme-delete-ns -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-delete-ns -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-delete-ns -s t -l timeout -d 'Override default timeout value 120,000.  In milliseconds'

