# nvme-sndk-namespace-resize
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-namespace-resize.1.gz
complete -c nvme-sndk-namespace-resize -s n -l namespace-id -d 'Namespace ID; ID of the namespace to resize'
complete -c nvme-sndk-namespace-resize -s o -l op-option -d 'Overprovisioning Option; defaults to 0xF Valid Values: 0x1 - 7% of Original T…'

