# nvme-solidigm-parse-telemetry-log
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-parse-telemetry-log.1.gz
complete -c nvme-solidigm-parse-telemetry-log -s g -l host-generate -d 'Controls when to generate a new host-initiated report'
complete -c nvme-solidigm-parse-telemetry-log -s c -l controller-init -d 'Gather report generated by the controller'
complete -c nvme-solidigm-parse-telemetry-log -s d -l data-area -d 'Pick which telemetry data area to report'
complete -c nvme-solidigm-parse-telemetry-log -s j -l config-file -d 'Specify a JSON configuration file for custom parsing of the telemetry log'
complete -c nvme-solidigm-parse-telemetry-log -s s -l source-file -d 'Specifies a binary file containing a telemetry log dump to parse instead of r…'

