# nvme-disconnect-all
# Autogenerated from man page /usr/share/man/man1/nvme-disconnect-all.1.gz
complete -c nvme-disconnect-all -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-disconnect-all -s v -l verbose -d 'Increase the information detail in the output'

