# nvme-ocp-set-dssd-async-event-config
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-set-dssd-async-event-config.1.gz
complete -c nvme-ocp-set-dssd-async-event-config -s e -l enable-panic-notices -d 'Set enable panic notices [0]'
complete -c nvme-ocp-set-dssd-async-event-config -s s -l save -d 'Save the attribute so that it persists through all power states and resets'

