# nvme-sndk-log-page-directory
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-log-page-directory.1.gz
complete -c nvme-sndk-log-page-directory -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

