# nvme-solidigm-vs-drive-info
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-vs-drive-info.1.gz
complete -c nvme-solidigm-vs-drive-info -s o -l output-format -d 'Set the reporting format to normal or json'

