# nvme-ocp-set-dssd-power-state-feature
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-set-dssd-power-state-feature.1.gz
complete -c nvme-ocp-set-dssd-power-state-feature -s p -l power-state -d 'DSSD Power State to set in watts'

