# nvme-io-mgmt-recv
# Autogenerated from man page /usr/share/man/man1/nvme-io-mgmt-recv.1.gz
complete -c nvme-io-mgmt-recv -s n -l namespace-id -d 'Use the provided namespace id for the command'
complete -c nvme-io-mgmt-recv -s d -l data -d 'File to write received data into'
complete -c nvme-io-mgmt-recv -s l -l data-len -d 'Received data buffer length'
complete -c nvme-io-mgmt-recv -s m -l mo -d 'Management Operation to perform'
complete -c nvme-io-mgmt-recv -s s -l mos -d 'Management Operation Specific parameter'
complete -c nvme-io-mgmt-recv -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-io-mgmt-recv -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-io-mgmt-recv -s t -l timeout -d 'Override default timeout value.  In milliseconds'

