# nvme-write-uncor
# Autogenerated from man page /usr/share/man/man1/nvme-write-uncor.1.gz
complete -c nvme-write-uncor -s s -l start-block -d 'Start block'
complete -c nvme-write-uncor -s c -l block-count -d 'Number of logical blocks to write uncorrectable'
complete -c nvme-write-uncor -s n -l namespace-id -d 'Namespace ID use in the command'
complete -c nvme-write-uncor -s T -l dir-type -d 'Directive type'
complete -c nvme-write-uncor -s S -l dir-spec -d 'Directive specific'
complete -c nvme-write-uncor -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-write-uncor -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-write-uncor -s t -l timeout -d 'Override default timeout value.  In milliseconds'

