# nvme-get-ns-id
# Autogenerated from man page /usr/share/man/man1/nvme-get-ns-id.1.gz
complete -c nvme-get-ns-id -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-get-ns-id -s v -l verbose -d 'Increase the information detail in the output'

