# nvme-solidigm-smart-log-add
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-smart-log-add.1.gz
complete -c nvme-solidigm-smart-log-add -s n -l namespace-id -d 'Retrieve the log for the given nsid'
complete -c nvme-solidigm-smart-log-add -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

