# nvme-solidigm-latency-tracking-log
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-latency-tracking-log.1.gz
complete -c nvme-solidigm-latency-tracking-log -s e -l enable -d 'Enable latency tracking before retrieving the log'
complete -c nvme-solidigm-latency-tracking-log -s d -l disable -d 'Disable latency tracking after retrieving the log'
complete -c nvme-solidigm-latency-tracking-log -s r -l read -d 'Retrieve read latency statistics (default if neither --read nor --write is sp…'
complete -c nvme-solidigm-latency-tracking-log -s w -l write -d 'Retrieve write latency statistics'
complete -c nvme-solidigm-latency-tracking-log -s t -l type -d 'Specify the log type to retrieve'
complete -c nvme-solidigm-latency-tracking-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

