# nvme-solidigm-market-log
# Autogenerated from man page /usr/share/man/man1/nvme-solidigm-market-log.1.gz
complete -c nvme-solidigm-market-log -s b -l raw-binary -d 'Output the raw log data in binary format'

