# nvme-verify
# Autogenerated from man page /usr/share/man/man1/nvme-verify.1.gz
complete -c nvme-verify -s n -l namespace-id -d 'Namespace ID use in the command'
complete -c nvme-verify -s s -l start-block -d 'Start block address'
complete -c nvme-verify -s c -l block-count -d 'Number of logical blocks to Verify'
complete -c nvme-verify -s l -l limited-retry -d 'Sets the limited retry flag'
complete -c nvme-verify -s f -l force-unit-access -d 'Set the force-unit access flag'
complete -c nvme-verify -s p -l prinfo -d 'Protection Information field definition'
complete -c nvme-verify -s r -l ref-tag -d 'Optional reftag when used with protection information'
complete -c nvme-verify -s m -l app-tag-mask -d 'Optional application tag mask when used with protection information'
complete -c nvme-verify -s a -l app-tag -d 'Optional application tag when used with protection information'
complete -c nvme-verify -s S -l storage-tag -d 'Variable Sized Expected Logical Block Storage Tag(ELBST)'
complete -c nvme-verify -s C -l storage-tag-check -d 'This flag enables Storage Tag field checking as part of Verify operation'
complete -c nvme-verify -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-verify -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-verify -s t -l timeout -d 'Override default timeout value.  In milliseconds'

