# nvme-ocp-error-recovery-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-error-recovery-log.1.gz
complete -c nvme-ocp-error-recovery-log -s o -l output-format -d 'Set the reporting format to normal or json or binary'

