# nvme-fw-download
# Autogenerated from man page /usr/share/man/man1/nvme-fw-download.1.gz
complete -c nvme-fw-download -s f -l fw -d 'Required argument'
complete -c nvme-fw-download -s x -l xfer -d 'This specifies the size to split each transfer'
complete -c nvme-fw-download -s O -l offset -d 'This specifies the starting offset in dwords'
complete -c nvme-fw-download -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-fw-download -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-fw-download -s t -l timeout -d 'Override default timeout value.  In milliseconds'

