# nvme-sndk-drive-resize
# Autogenerated from man page /usr/share/man/man1/nvme-sndk-drive-resize.1.gz
complete -c nvme-sndk-drive-resize -s s -l size -d 'The new size (in GB) to resize the drive to'

