# nvme-resv-acquire
# Autogenerated from man page /usr/share/man/man1/nvme-resv-acquire.1.gz
complete -c nvme-resv-acquire -s n -l namespace-id -d 'Override the nsid field'
complete -c nvme-resv-acquire -s c -l crkey -d 'Current Reservation Key: The field specifies the current reservation key asso…'
complete -c nvme-resv-acquire -s p -l prkey -d 'Preempt Reservation Key: If the Reservation Acquire Action is set to 001b (i'
complete -c nvme-resv-acquire -s t -l rtype -d 'Reservation Type: This field specifies the type of reservation to be created'
complete -c nvme-resv-acquire -s a -l racqa -d 'Reservation Acquire Action: This field specifies the action that is performed…'
complete -c nvme-resv-acquire -s i -l iekey -d 'Ignore Existing Key: If this bit is set to a 1, then the Current Reservation …'
complete -c nvme-resv-acquire -s o -l output-format -d 'Set the reporting format to normal, json or binary'
complete -c nvme-resv-acquire -s v -l verbose -d 'Increase the information detail in the output'
complete -c nvme-resv-acquire -l timeout -d 'Override default timeout value.  In milliseconds'

