# nvme-sed-unlock
# Autogenerated from man page /usr/share/man/man1/nvme-sed-unlock.1.gz
complete -c nvme-sed-unlock -s r -l read-only -d 'Set locking range to read-only'
complete -c nvme-sed-unlock -s k -l ask-key -d 'Prompt for SED authentication key'

