# offload-build
# Autogenerated from man page /usr/share/man/man1/offload-build.1.gz
complete -c offload-build -s r -l repo
complete -c offload-build -s a -l arch
complete -c offload-build -s s -l server
complete -c offload-build -s h -l help

