# pacquery
# Autogenerated from man page /usr/share/man/man1/pacquery.1.gz
complete -c pacquery -l repos -d Repositories
complete -c pacquery -l dbpath -d 'The path to the pacman database, default ( /var/lib/pacman )'
complete -c pacquery -s h -l help -d 'Print help'

