# pkgctl-issue-view
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-view.1.gz
complete -c pkgctl-issue-view -s p -l package
complete -c pkgctl-issue-view -s c -l comments
complete -c pkgctl-issue-view -s w -l web
complete -c pkgctl-issue-view -s h -l help

