# pkgctl-version-upgrade
# Autogenerated from man page /usr/share/man/man1/pkgctl-version-upgrade.1.gz
complete -c pkgctl-version-upgrade -l no-update-checksums
complete -c pkgctl-version-upgrade -s v -l verbose
complete -c pkgctl-version-upgrade -s h -l help

