# pkgctl-aur-drop-from-repo
# Autogenerated from man page /usr/share/man/man1/pkgctl-aur-drop-from-repo.1.gz
complete -c pkgctl-aur-drop-from-repo -l no-disown
complete -c pkgctl-aur-drop-from-repo -s f -l force
complete -c pkgctl-aur-drop-from-repo -s h -l help

