# pkgctl-db-remove
# Autogenerated from man page /usr/share/man/man1/pkgctl-db-remove.1.gz
complete -c pkgctl-db-remove -l partial
complete -c pkgctl-db-remove -s a -l arch
complete -c pkgctl-db-remove -l noconfirm
complete -c pkgctl-db-remove -s h -l help

