# pkgctl-repo-configure
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-configure.1.gz
complete -c pkgctl-repo-configure -l protocol
complete -c pkgctl-repo-configure -s j -l jobs
complete -c pkgctl-repo-configure -s h -l help

