# pkgctl-release
# Autogenerated from man page /usr/share/man/man1/pkgctl-release.1.gz
complete -c pkgctl-release -s m -l message
complete -c pkgctl-release -s r -l repo
complete -c pkgctl-release -s s -l staging
complete -c pkgctl-release -s t -l testing
complete -c pkgctl-release -s u -l db-update
complete -c pkgctl-release -s h -l help

