# pkgctl-issue-list
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-list.1.gz
complete -c pkgctl-issue-list -s g -l group
complete -c pkgctl-issue-list -s w -l web
complete -c pkgctl-issue-list -s h -l help
complete -c pkgctl-issue-list -s A -l all
complete -c pkgctl-issue-list -s c -l closed
complete -c pkgctl-issue-list -s U -l unconfirmed
complete -c pkgctl-issue-list -l search
complete -c pkgctl-issue-list -l in
complete -c pkgctl-issue-list -s l -l label
complete -c pkgctl-issue-list -l confidentiality
complete -c pkgctl-issue-list -l priority
complete -c pkgctl-issue-list -l resolution
complete -c pkgctl-issue-list -l scope
complete -c pkgctl-issue-list -l severity
complete -c pkgctl-issue-list -l status
complete -c pkgctl-issue-list -l assignee
complete -c pkgctl-issue-list -l assigned-to-me
complete -c pkgctl-issue-list -l author
complete -c pkgctl-issue-list -l created-by-me

