# pkgctl-repo-switch
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-switch.1.gz
complete -c pkgctl-repo-switch -l discard-changes
complete -c pkgctl-repo-switch -s f -l force
complete -c pkgctl-repo-switch -s h -l help

