# pkgctl-version-check
# Autogenerated from man page /usr/share/man/man1/pkgctl-version-check.1.gz
complete -c pkgctl-version-check -s h -l help
complete -c pkgctl-version-check -s v -l verbose
complete -c pkgctl-version-check -l json
complete -c pkgctl-version-check -s F -l format

