# pkgctl-version-setup
# Autogenerated from man page /usr/share/man/man1/pkgctl-version-setup.1.gz
complete -c pkgctl-version-setup -s f -l force
complete -c pkgctl-version-setup -l prefer-platform-api
complete -c pkgctl-version-setup -l url
complete -c pkgctl-version-setup -l no-check
complete -c pkgctl-version-setup -l no-upstream
complete -c pkgctl-version-setup -s h -l help

