# pkgctl-issue-create
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-create.1.gz
complete -c pkgctl-issue-create -s p -l package
complete -c pkgctl-issue-create -s t -l title
complete -c pkgctl-issue-create -s F -l file
complete -c pkgctl-issue-create -s e -l edit
complete -c pkgctl-issue-create -s w -l web
complete -c pkgctl-issue-create -l recover
complete -c pkgctl-issue-create -l confidentiality
complete -c pkgctl-issue-create -l priority
complete -c pkgctl-issue-create -l scope
complete -c pkgctl-issue-create -l severity
complete -c pkgctl-issue-create -l status
complete -c pkgctl-issue-create -s h -l help

