# pkgctl-issue-close
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-close.1.gz
complete -c pkgctl-issue-close -s p -l package
complete -c pkgctl-issue-close -s m -l message
complete -c pkgctl-issue-close -s e -l edit
complete -c pkgctl-issue-close -s r -l resolution
complete -c pkgctl-issue-close -s h -l help

