# pkgctl-issue-reopen
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-reopen.1.gz
complete -c pkgctl-issue-reopen -s p -l package
complete -c pkgctl-issue-reopen -s m -l message
complete -c pkgctl-issue-reopen -s e -l edit
complete -c pkgctl-issue-reopen -s h -l help

