# pkgctl-issue-comment
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-comment.1.gz
complete -c pkgctl-issue-comment -s p -l package
complete -c pkgctl-issue-comment -s m -l message
complete -c pkgctl-issue-comment -s e -l edit
complete -c pkgctl-issue-comment -s h -l help

