# pkgctl-repo-clone
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-clone.1.gz
complete -c pkgctl-repo-clone -s m -l maintainer
complete -c pkgctl-repo-clone -l protocol
complete -c pkgctl-repo-clone -l universe
complete -c pkgctl-repo-clone -l switch
complete -c pkgctl-repo-clone -s j -l jobs
complete -c pkgctl-repo-clone -s h -l help

