# pkgctl-repo-clean
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-clean.1.gz
complete -c pkgctl-repo-clean -s i -l interactive
complete -c pkgctl-repo-clean -s n -l dry-run
complete -c pkgctl-repo-clean -s h -l help

