# pkgctl-issue-edit
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-edit.1.gz
complete -c pkgctl-issue-edit -s p -l package
complete -c pkgctl-issue-edit -s t -l title
complete -c pkgctl-issue-edit -s e -l edit
complete -c pkgctl-issue-edit -l recover
complete -c pkgctl-issue-edit -l confidentiality
complete -c pkgctl-issue-edit -l priority
complete -c pkgctl-issue-edit -l resolution
complete -c pkgctl-issue-edit -l scope
complete -c pkgctl-issue-edit -l severity
complete -c pkgctl-issue-edit -l status
complete -c pkgctl-issue-edit -s h -l help

