# pkgctl-issue-move
# Autogenerated from man page /usr/share/man/man1/pkgctl-issue-move.1.gz
complete -c pkgctl-issue-move -s p -l package
complete -c pkgctl-issue-move -s m -l message
complete -c pkgctl-issue-move -s e -l edit
complete -c pkgctl-issue-move -s h -l help

