# signoff
# Autogenerated from man page /usr/share/man/man1/signoff.1.gz
complete -c signoff -s s -l signoff -d 'Signoff the specified package'
complete -c signoff -s r -l revoke -d 'Revoke the specified package'
complete -c signoff -s l -l list -d 'List of packages that can be signed off'
complete -c signoff -s i -l interactive -d 'Interactively sign off packages'
complete -c signoff -s u -l uninstalled -d 'Include uninstalled packages when listing'
complete -c signoff -s a -l signed-off -d 'Include signed-off packages when listing'
complete -c signoff -s q -l quiet -d 'Be less verbose when listing packages'
complete -c signoff -s b -l db-path -d 'pacman database path'
complete -c signoff -l username -d 'ArchWeb username'
complete -c signoff -l password -d 'ArchWeb password'
complete -c signoff -l noconfirm -d 'Don\'t ask for confirmation'
complete -c signoff -l nocolor -d 'Don\'t use color in output'
complete -c signoff -s h -l help -d 'Show this message and exit'

