# sudo_sendlog
# Autogenerated from man page /usr/share/man/man8/sudo_sendlog.8.gz
complete -c sudo_sendlog -s A -l accept-only -d 'Only send the accept event, not the I/O associated with the log'
complete -c sudo_sendlog -s b -l ca-bundle -d 'The path to a certificate authority bundle file, in PEM format, to use instea…'
complete -c sudo_sendlog -s c -l cert -d 'The path to the client\'s certificate file in PEM format'
complete -c sudo_sendlog -l help
complete -c sudo_sendlog -s h -l host -d 'Connect to the specified host instead of localhost'
complete -c sudo_sendlog -s i -l iolog-id -d 'Use the specified iolog-id when restarting a log transfer'
complete -c sudo_sendlog -s r -d option
complete -c sudo_sendlog -s k -l key -d 'The path to the client\'s private key file in PEM format'
complete -c sudo_sendlog -s n -l no-verify -d 'If specified, the server\'s certificate will not be verified during the TLS ha…'
complete -c sudo_sendlog -s p -l port -d 'Use the specified network port when connecting to the log server instead of t…'
complete -c sudo_sendlog -l restart -d 'Restart an interrupted connection to the log server'
complete -c sudo_sendlog -s R -l reject -d 'Send a reject event for the command using the specified reject-reason, even t…'
complete -c sudo_sendlog -s s -l stop-after -d 'Stop sending log records and close the connection when stop-point is reached'
complete -c sudo_sendlog -s t -l test -d 'Open number simultaneous connections to the log server and send the specified…'
complete -c sudo_sendlog -s V -l version -d 'Print the sudo_sendlog version and exit'

