# xcolor
# Autogenerated from man page /usr/share/man/man1/xcolor.1.gz
complete -c xcolor -s f -l format -d 'Specify output format'
complete -c xcolor -s c -l custom -d 'Specify template for custom output format'
complete -c xcolor -s s -l selection -d 'Save output to X11 selection'
complete -c xcolor -s S -l scale -d 'Magnification scale of the picker, defaults to 8'
complete -c xcolor -s P -l preview-size -d 'Pixel size of the picker, defaults to 255'
complete -c xcolor -s v -l version -d 'Print version information and exit'
complete -c xcolor -s h -l help -d 'Print help message and exit'

