# xfce4-dict
# Autogenerated from man page /usr/share/man/man1/xfce4-dict.1.gz
complete -c xfce4-dict -s h -l help -d 'Show help options'
complete -c xfce4-dict -l help-all -d 'Show all help options'
complete -c xfce4-dict -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfce4-dict -s d -l dict -d 'Search the given text using a Dict server(RFC 2229)'
complete -c xfce4-dict -s w -l web -d 'Search the given text using a web-based search engine'
complete -c xfce4-dict -s s -l spell -d 'Check the given text with a spell checker'
complete -c xfce4-dict -s t -l text-field -d 'Grab the focus on the text field in the panel'
complete -c xfce4-dict -s i -l ignore-plugin -d 'Start stand-alone application even if the panel plugin is loaded'
complete -c xfce4-dict -s c -l clipboard -d 'Grabs the PRIMARY selection content and uses it as search text'
complete -c xfce4-dict -s v -l verbose -d 'Be verbose'
complete -c xfce4-dict -s V -l version -d 'Show version information'
complete -c xfce4-dict -l display -d 'X display to use COPYRIGHT Copyright © 2006-2023 Xfce Development Team'

