# xfce4-popup-whiskermenu
# Autogenerated from man page /usr/share/man/man1/xfce4-popup-whiskermenu.1.gz
complete -c xfce4-popup-whiskermenu -s h -l help -d 'Show help options'
complete -c xfce4-popup-whiskermenu -s p -l pointer -d 'Popup menu at current mouse position'
complete -c xfce4-popup-whiskermenu -s c -l center -d 'Popup menu at center of screen'
complete -c xfce4-popup-whiskermenu -s l -l list -d 'Print available menu instance IDs'
complete -c xfce4-popup-whiskermenu -s i -l instance -d 'Choose which menu to popup by instance ID'

